Сравнить две матрицы со случайными значениями на равенство
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [1]:
import numpy as  np

In [2]:
rnd = np.random.default_rng()
A = rnd.integers(-30, 30, (10, 10))
B = rnd.integers(-30, 30, (10, 10))
print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Result of operation:")
if np.array_equal(A,B):
    print("Matrix equal")
else:
    print("Matrix not equal")

Matrix A:
 [[ 26 -16  -4 -15  13 -27  -6 -23 -16 -16]
 [-14 -15 -25  27 -26  -8  10 -12 -13 -28]
 [-17  -3  22   8 -28  20  14  12 -10  16]
 [  1 -23  14  17 -18  11 -25   0   2  10]
 [-30  27 -15 -24  15 -21  18  24  17  -8]
 [-23  16 -30  23 -21   1  25   7  19   3]
 [-15 -25  19 -23 -12  -4  13  12  21  24]
 [  7  13  12  27 -12 -16  -7   2 -16 -20]
 [ 27  -9  25  16 -30   9  -5  29 -25   3]
 [-10  -3  -9 -22 -24  19  24 -20  23  19]]
Matrix B:
 [[ 14   2   2  28   4  -3 -21 -29  -1  25]
 [-30 -12  20  -8   4 -23  -6   6  12  14]
 [ -1  24   4 -11  24   6 -30  29  13  26]
 [ 29 -26 -23 -12  22 -24  24  -5  18  24]
 [-20   6   3  10  15 -28  -8  -9   0  24]
 [ -9   5 -13  -9   5   6  14  -1  18 -17]
 [ -3  -3 -14  12 -27 -20 -12   5   4  16]
 [ 15 -22  11  -3   2 -29 -14  18 -19  10]
 [  7  18  -1 -21  14 -25  25 -26   8   4]
 [ 23  13  18 -22   9 -19   0   7 -18  14]]
Result of operation:
Matrix not equal
